CREATE TABLE people(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    MOMENTO TIMESTAMP NOT NULL,
    NOMBRE  VARCHAR(20) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(50),
    EDAD INT,
    NOTA VARCHAR(40),
    PRIMARY KEY (ID))